package com.njbrady.transmute

val dadJokes = listOf(
    "What did one plate whisper to the other plate? Dinner is on me.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Two sheep walk into a—baaaa.",
    "Stop looking for the perfect match; use a lighter.",
    "Try the seafood diet—you see food, then you eat it.",
    " Did you hear the rumor about butter? Well, I'm not going to go spreading it!",
    "What's Forrest Gump's password? 1forrest1",
    "What state is known for its small drinks? Minnesota.",
    "What does a nosey pepper do? It gets jalapeño business.",
    " If two vegetarians get in an argument, is it still called beef?",
    "How do you deal with a fear of speed bumps? You slowly get over it.",
    "What concert would cost only 45 cents? 50 Cent featuring Nickelback!",
    "How do you measure the mass of an influencer's following? By Instagrams!"
)

val cities = listOf(
    "Warner, NH",
    "East Natchitoches, PA",
    "Lyon, WV",
    "Willow Run, IL",
    "Conyersville, AZ",
    "Mount Baker, NY",
    "Farmington Lake, OK",
    "Martins Corner, TX",
    "Pickerel Narrows, MT",
    "Willaha, OH",
    "Center, MA",
    "Spring City, MS",
    "Mittenlane, TX",
    "East Waterford, ME",
    "Coltman, WV",
    "Scottsville, KS",
    "Hebron, AZ",
    "Longview, MA",
    "Emerson, MT",
    "North Knoxville, AL",
    "Momford Landing, IN",
    "Ipswich, IA",
    "Storms, TX",
    "Kalauao, SD",
    "Farwell, FL",
    "Brentwood Village, MT",
    "Wilhelm Park, MT",
    "Bannister Acres, NC",
    "Bent Pine, VA",
    "Mitchell, AZ",
    "Social Circle, MO",
    "Kreutzberg, NY",
    "Cimarron, WA",
    "Brookhaven, DC",
    "Montverde Junction, NJ",
    "Midland City, AK",
    "Sacramento, ME",
    "Del Rey Oaks, RI",
    "Coal Creek, OK",
    "Rabbitown, TN",
    "Fairland, GA",
    "Gaskil, DE",
    "Morgan Mill, OK",
    "Merrimac South, AL",
    "Stanardsville, NH",
    "Two Brooks, WI",
    "Curriers, NM",
    "Skookumchuck, VA",
    "Edgerton, RI",
    "Slater, MO")